# Obfuscated by Mr.X
import base64
exec(base64.b64decode('aW1wb3J0IHJhbmRvbSAKaW1wb3J0IG9zIApudW09cmFuZG9tLnJhbmRpbnQoMSwzKQpwcmludChudW0pCm9zLnN5c3RlbSgiY2xlYXIiKQpwcmludCgiXDAzM1sxbVwwMzNbMzNtW1wwMzNbMzJtLS0tQm9vdGluZy0tXDAzM1szM21dXDAzM1swbSIpCgoKIyBDb25kaXRpb24gCgppZiBudW0gPT0gMToKICAgIG9zLnN5c3RlbSgibXB2IEFjY2Vzcy1HcmFudGVkLm1wMyIpCmVsaWYgbnVtPT0yOgogICAgb3Muc3lzdGVtKCJtcHYgSmFydmlzMi5tcDMiKQplbHNlIDoKICAgIG9zLnN5c3RlbSgibXB2IEpBUlZJUy5tcDMiKQogCiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMK').decode('utf-8'))
